名称：Docker镜像CI: Docker Image CI

在：:
  推送::
    分支: [ "main" ]: [ "main" ]
  拉取请求::
    分支: [ "main" ]: [ "main" ]

职位::

  构建::

    运行于: ubuntu-latest: ubuntu-latest

    步骤：:
    - 使用：actions/checkout@v4uses: actions/checkout@v4
    - name: 构建Docker镜像name: Build the Docker image
      运行: docker build . --file Dockerfile --tag my-image-name:$(date +%s): docker build . --file Dockerfile --tag my-image-name:$(date +%s)
